version: '3.1'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:12.3.0'
    ports:
      - '5432:5432'
    volumes:
      - "${storage:?Please supply storage environment variable}/db:/bitnami/postgresql"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=hal
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=hal
  
  apache:
    build: .
    volumes:
     - "${storage:?Please supply storage environment variable}/logs:/var/log/apache2"
    ports:
      - '80:80'
    