version: '3.1'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:13.3.0'
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - "${storage:?Please supply storage in environment variable}/db:/bitnami/postgresql"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=hal
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=hal
  
  apache:
    image: hal:${version:?Please supply version in .env}
    build: .
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
     - "${storage:?Please supply storage environment variable}/logs:/var/log/apache2"
    environment:
      - PGHOST=postgresql
      - PGPORT=5432
      - PGDATABASE=hal
      - PGUSER=hal
      - PGPASSWORD=password123
      
    