#!/usr/bin/perl -w
use strict;
use FindBin qw ($Bin);

chdir "$Bin";
$ENV{storage} = "$Bin/docker";
my $lastTime = 0;

sub getTime() {
    my $newest = 0;
    for my $f (split /\n/, `find -type f`) {
	next if $f =~ m!/(config|\.svn|static)/!;
	next if $f =~ m!/[~#]$/!;
	next if $f =~ m!/\.!;
	next if $f =~ m!/var/!;
	next if $f =~ m!^\./docker!;
	
	my $t = (stat $f)[9];
	print "$f has changed\n" if $lastTime && $t > $lastTime;
	$newest = $t if $t > $newest;
    }
    return $newest;
}

while (1) {
    my $t = getTime();
    
    if ($t != $lastTime) {
	print STDERR "\nRestarting apache";
	$lastTime = $t;
	if (system("docker-compose build apache")) {
	    print STDERR "Build failed\n";
	} else {
	    system("docker rm -f hal_apache_1");
	    if (system("docker-compose up -d apache")) {
		print STDERR "Start failed\n";
	    }
	}

	print STDERR "\nWaiting for changes";
    } else {
	print STDERR ".";
    }
    
    sleep 1;
}
