#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin $Script);
use lib "$Bin/../pm";
use Data::Dumper;
use utf8;

use HAL;
use HAL::DB;
use HAL::Util;


my $db = new HAL::DB;

my $ct = $db->sql("select id, passwd from member where passwd like 'sha256:%' order by id") or die "Urgh";
while (my ($id, $old) = $ct->fetchrow_array) {
    my $shabby = shabbyPassword($old) or die "Urgh";    
    $db->sql('update member set passwd=? where id=?', $shabby, $id) or die;
    print "update member set passwd='$shabby' where id=$id and passwd='$old'\n";
    $db->dbh->commit;
}
$ct->finish;

