#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);
use HTML::Entities;
use Email::Valid;
use utf8;
use Time::HiRes qw(gettimeofday);
use lib "$Bin/../pm";

use HAL;
use HAL::DB;
use HAL::Util;
use HAL::Email;

my $hashed1 = passwordHash("testHest");
my $t0 = gettimeofday;
my $hashed3 = passwordHash("PestFest");
my $t1 = gettimeofday;

my $t = $t1-$t0;
print STDERR "Time: $t\t$hashed1\n";

die "'$hashed1' == '$hashed3'" if $hashed1 eq $hashed3;

die "Urgh" unless passwordVerify($hashed1, "testHest");
die "Urgh" unless passwordVerify($hashed3, "PestFest");

my $bcrypt11 = 'bcrypt:3fc313884e148c12:11:9qJ08eTdzqwxrlluZzW2y.vzwN7E2Se';
die "Urgh" unless passwordVerify($bcrypt11, "testHest");

my $sha256 = 'sha256:test:c7a976b9ca8a3ecf9e62257d78d571dc4bfbc3aa9320cec1411ccd9e9961b359';
die "Urgh" unless passwordVerify($sha256, "hest");

my $shabby = shabbyPassword($sha256) or die "Urgh";
die "Urgh" unless passwordVerify($shabby, "hest");
print STDERR "Shabby: $shabby\n";
